[package]
name = "ethos-fuzz-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
ethos-fuzz = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "schema_oracle"
path = "fuzz_targets/schema_oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "schema"
path = "fuzz_targets/schema.rs"
test = false
doc = false
bench = false
