//! Project setup and metadata generation for the pipeline.
//!
//! This module handles project scaffolding, Cargo.toml generation, README creation,
//! and other project metadata files.

use std::fs;
use std::path::Path;

use types::{Implementation, ProtocolVersion};

use crate::PipelineError;

/// Setup project files (Cargo.toml, README, license, .gitignore)
///
/// # Arguments
///
/// * `crate_root` - Path to the crate root directory
/// * `target_version` - The target protocol version
/// * `artifact_name` - The artifact name for the generated crate
///
/// # Returns
///
/// Returns `Result<()>` indicating success or failure
pub fn setup_project_files(
    crate_root: &Path,
    target_version: &ProtocolVersion,
    artifact_name: Implementation,
) -> Result<(), PipelineError> {
    write_cargo_toml(crate_root, target_version, artifact_name)?;

    let gitignore_path = crate_root.join(".gitignore");
    fs::write(&gitignore_path, "/target\n/Cargo.lock\n")?;

    write_readme(crate_root, target_version, artifact_name)?;
    write_license(crate_root)?;

    Ok(())
}

/// Write the Cargo.toml file for the generated crate
///
/// # Arguments
///
/// * `root` - The root directory of the generated crate
/// * `target_version` - The implementation version being targeted
/// * `artifact_name` - The artifact name for the generated crate (e.g., "bitcoin-core", "lightning")
///
/// # Returns
///
/// Returns `Result<()>` indicating success or failure of writing the Cargo.toml file
pub fn write_cargo_toml(
    root: &Path,
    target_version: &ProtocolVersion,
    artifact_name: Implementation,
) -> Result<(), PipelineError> {
    let version = target_version.crate_version();
    let protocol_version = target_version.as_str().trim_start_matches('v');

    // Use hardcoded published crate name
    let crate_name = artifact_name.published_crate_name();
    let toml = format!(
        r#"[workspace]

[package]
publish = true

name = "{}"
version = "{}"
edition = "2021"
authors = ["Ethos Core Developers"]
license = "CC0-1.0"
description = "Generated client for {} v{}."
readme = "README.md"
keywords = ["bitcoin", "protocol", "compiler", "integration-testing"]
categories = ["cryptography", "data-structures", "api-bindings"]
repository = "https://github.com/nervana21/ethos"
homepage = "https://github.com/nervana21/ethos"
documentation = "https://docs.rs/{}"

[dependencies]
async-trait = "0.1.89"
bitcoin = {{ version = "0.32.8", features = ["rand", "serde"] }}
reqwest = {{ version = "0.12.26", default-features = false, features = [
    "json",
    "rustls-tls",
] }}
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = {{ version = "1.0.145", features = ["preserve_order"] }}
tempfile = "3.8.2"
thiserror = "2.0.12"
tokio = {{ version = "1", features = ["full"] }}
tracing = "0.1.39"

[features]
serde-deny-unknown-fields = []
"#,
        crate_name,
        version,
        artifact_name.as_str(),
        protocol_version,
        crate_name,
    );

    fs::write(root.join("Cargo.toml"), toml)?;
    Ok(())
}

/// Write the README.md file for the generated crate
///
/// # Arguments
///
/// * `root` - The root directory of the generated crate
/// * `target_version` - The implementation version being targeted
/// * `artifact_name` - The artifact name for the generated crate (e.g., "bitcoin-core", "lightning")
///
/// # Returns
///
/// Returns `Result<()>` indicating success or failure of writing the README.md file
pub fn write_readme(
    root: &Path,
    target_version: &ProtocolVersion,
    artifact_name: Implementation,
) -> Result<(), PipelineError> {
    let _version = target_version.crate_version();
    let crate_name = artifact_name.published_crate_name();

    // Determine protocol-specific content
    let protocol_name = artifact_name.display_name();
    let executable_name = artifact_name.executable_name();
    let test_client_name = artifact_name.test_client_prefix();
    let example_method = artifact_name.example_method();
    let example_description = artifact_name.example_description();

    let readme = format!(
        r#"# {crate_name}

[![License: CC0-1.0](https://img.shields.io/badge/license-CC0--1.0-blue)](LICENSE)
[![Docs.rs](https://img.shields.io/docsrs/{crate_name})](https://docs.rs/{crate_name})
[![crates.io](https://img.shields.io/crates/v/{crate_name})](https://crates.io/crates/{crate_name})

Type-safe Rust client for {protocol_name} v{version} RPCs, supporting integration testing with locally-started nodes. Generated by the ethos toolchain.

## Why Use This?

This client aims to provide:
- Less repetitive boilerplate
- Easier upgrades across protocol versions
- Compile-time type checks for RPC requests/responses
- Managed integration testing (spawns protocol daemons as subprocesses, handles ports)

## Project Structure

- `client_trait/`: Rust traits for {protocol_name} RPC endpoints
- `node/`: Node manager for process orchestration in integration environments
- `{crate_name}_clients/`: Utilities for driving integration tests against spawned local nodes
- `transport/`: Async transport layer with batching and error handling
- `types/`: Typed response structs and enums for all RPC methods

## Example

This async example (using [Tokio](https://tokio.rs)) demonstrates integration testing with a spawned node:

```toml
[dependencies]
{crate_name} = "{version}"
tokio = {{ version = "1", features = ["full"] }}
```

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let manager = crate::node::BitcoinNodeManager::new()?;
    manager.start().await?;
    let transport = manager.create_transport().await?;
    let client = crate::{test_client_name}::new(transport);
    let result = client.{example_method}().await?;
    println!("{example_description}: {{:?}}", result);
    manager.stop().await?;
    Ok(())
}}
```

## Requirements
Requires a working `{executable_name}` (`bitcoind`, `lightningd`, etc.) in `$PATH`.

## About
This crate is generated by [ethos](https://github.com/nervana21/ethos). Its code is kept synchronized with upstream protocol changes through code generation.

## Contributing
See [CONTRIBUTING.md](CONTRIBUTING.md).

## License
Ethos is released under the terms of the CC0-1.0 license. See [LICENSE](LICENSE) for details.

## Security
This library launches {protocol_name} daemons for local integration testing. For real network use, use strong network/firewall controls and carefully audit all dependencies.
"#,
        crate_name = crate_name,
        protocol_name = protocol_name,
        version = target_version.crate_version(),
        executable_name = executable_name,
        test_client_name = test_client_name,
        example_method = example_method,
        example_description = example_description
    );

    fs::write(root.join("README.md"), readme)?;
    Ok(())
}

/// Write the LICENSE.md file for the generated crate
pub fn write_license(root: &Path) -> Result<(), PipelineError> {
    let license = r#"CC0-1.0 Universal

Statement of Purpose

The laws of most jurisdictions throughout the world automatically confer
exclusive Copyright and Related Rights (defined below) upon the creator
and subsequent owner(s) (each and all, an "owner") of an original work of
authorship and/or a database (each, a "Work").

Certain owners wish to permanently relinquish those rights to a Work for
the purpose of contributing to a commons of creative, cultural and
scientific works ("Commons") that the public can reliably and without fear
of later claims of infringement build upon, modify, incorporate in other
works, reuse and redistribute as freely as possible in any form whatsoever
and for any purposes, including without limitation commercial purposes.
These owners may contribute to the Commons to promote the ideal of a free
culture and the further production of creative, cultural and scientific
works, or to gain reputation or greater distribution for their Work in
part through the use and efforts of others.

For these and/or other purposes and motivations, and without any
expectation of additional consideration or compensation, the person
associating CC0 with a Work (the "Affirmer"), to the extent that he or she
is an owner of Copyright and Related Rights in the Work, voluntarily
elects to apply CC0 to the Work and publicly distribute the Work under its
terms, with knowledge of his or her Copyright and Related Rights in the
Work and the meaning and intended legal effect of CC0 on those rights.

1. Copyright and Related Rights. A Work made available under CC0 may be
protected by copyright and related or neighboring rights ("Copyright and
Related Rights"). Copyright and Related Rights include, but are not
limited to, the following:

  i. the right to reproduce, adapt, distribute, perform, display,
     communicate, and translate a Work;
 ii. moral rights retained by the original author(s) and/or performer(s);
iii. publicity and privacy rights pertaining to a person's image or
     likeness depicted in a Work;
 iv. rights protecting against unfair competition in regards to a Work,
     subject to the limitations in paragraph 4(a), below;
  v. rights protecting the extraction, dissemination, use and reuse of data
     in a Work;
 vi. database rights (such as those arising under Directive 96/9/EC of the
     European Parliament and of the Council of 11 March 1996 on the legal
     protection of databases, and under any national implementation
     thereof, including any amended or successor version of such
     directive); and
vii. other similar, equivalent or corresponding rights throughout the
     world based on applicable law or treaty, and any national
     implementations thereof.

2. Waiver. To the greatest extent permitted by, but not in contravention
of, applicable law, Affirmer hereby overtly, fully, permanently,
irrevocably and unconditionally waives, abandons, and surrenders all of
Affirmer's Copyright and Related Rights and associated claims and causes
of action, whether now known or unknown (including existing as well as
future claims and causes of action), in the Work (i) in all territories
worldwide, (ii) for the maximum duration provided by applicable law or
treaty (including future time extensions), (iii) in any current or future
medium and for any number of copies, and (iv) for any purpose whatsoever,
including without limitation commercial, advertising or promotional
purposes (the "Waiver"). Affirmer makes the Waiver for the benefit of each
member of the public at large and to the detriment of Affirmer's heirs and
successors, fully intending that such Waiver shall not be subject to
revocation, rescission, cancellation, termination, or any other legal or
equitable action to disrupt the quiet enjoyment of the Work by the public
as contemplated by Affirmer's express Statement of Purpose.

3. Public License Fallback. Should any part of the Waiver for any reason
be judged legally invalid or ineffective under applicable law, then the
Waiver shall be preserved to the maximum extent permitted taking into
account Affirmer's express Statement of Purpose. In addition, to the
extent the Waiver is so judged Affirmer hereby grants to each affected
person a royalty-free, non transferable, non sublicensable, non exclusive,
irrevocable and unconditional license to exercise Affirmer's Copyright and
Related Rights in the Work (i) in all territories worldwide, (ii) for the
maximum duration provided by applicable law or treaty (including future
time extensions), (iii) in any current or future medium and for any number
of copies, and (iv) for any purpose whatsoever, including without
limitation commercial, advertising or promotional purposes (the
"License"). The License shall be deemed effective as of the date CC0 was
applied by Affirmer to the Work. Should any part of the License for any
reason be judged legally invalid or ineffective under applicable law, such
partial invalidity or ineffectiveness shall not invalidate the remainder
of the License, and in such case Affirmer hereby affirms that he or she
will not (i) exercise any of his or her remaining Copyright and Related
Rights in the Work or (ii) assert any associated claims and causes of
action with respect to the Work, in either case contrary to Affirmer's
express Statement of Purpose.

4. Limitations and Disclaimers.

 a. No trademark or patent rights held by Affirmer are waived, abandoned,
    surrendered, licensed or otherwise affected by this document.
 b. Affirmer offers the Work as-is and makes no representations or
    warranties of any kind concerning the Work, express, implied,
    statutory or otherwise, including without limitation warranties of
    title, merchantability, fitness for a particular purpose, non
    infringement, or the absence of latent or other defects, accuracy, or
    the present or absence of errors, whether or not discoverable, all to
    the greatest extent permissible under applicable law.
 c. Affirmer disclaims responsibility for clearing rights of other persons
    that may apply to the Work or any use thereof, including without
    limitation any person's Copyright and Related Rights in the Work.
    Further, Affirmer disclaims responsibility for obtaining any necessary
    consents, permissions or other rights required for any use of the
    Work.
 d. Affirmer understands and acknowledges that Creative Commons is not a
    party to this document and has no duty or obligation with respect to
    this CC0 or use of the Work.

For more information, please see
<http://creativecommons.org/publicdomain/zero/1.0/>"#;

    fs::write(root.join("LICENSE.md"), license)?;
    Ok(())
}
